name: Android APK Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Project
        run: |
          # Yeni yuklediyin fayli acir
          unzip -o kozmetik-envanteri.zip
          
          # Gradlew faylinin hansi qovluqda oldugunu tapir
          GRADLE_DIR=$(find . -name "gradlew" -printf '%h\n' | head -n 1)
          if [ -z "$GRADLE_DIR" ]; then echo "XETA: gradlew tapilmadi!"; exit 1; fi
          
          # Butun fayllari islek veziyyete getirir
          chmod +x "$GRADLE_DIR/gradlew"
          echo "PROJECT_PATH=$GRADLE_DIR" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build APK
        run: |
          cd ${{ env.PROJECT_PATH }}
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kosmetik-tətbiqi
          path: "**/build/outputs/apk/debug/*.apk"
